### ISSUE TITLE
minimal builsd is failing

### ISSUE THREAD

**Issue by LeOS-GSI** [home-assistant/companion.home-assistant#1038]
I have followed the all steps in your readme. But I stuck here 

3. Create a Firebase project at [Firebase Console](https://console.firebase.google.com)

4. Create four Android apps, with following package names 
 - `io.homeassistant.companion.android`
 - `io.homeassistant.companion.android.debug`
 - `io.homeassistant.companion.android.minimal`
 - `io.homeassistant.companion.android.minimal.debug`

5. Now download the `google-services.json` file and put it in the project's _/app_, _/automotive_ and _/wear_ folders. This file contains the configuration of the whole project (all four applications). ([You can also use the mock services file instead of generating your own](/.github/mock-google-services.json). The file should contain client IDs for all packages listed above for debugging to work properly.  **If you do not generate your own file FCM push notification will never work, only websocket notifications will**)

I can't create a firebase project, because I don't own any google account

I have placed the mockgoogle-service.json (as google-services.json) file in both locations 
_/media/ich/1TB_SSD/AndroidApks/temp/android/common/ 
 /media/ich/1TB_SSD/AndroidApks/temp/android/wear_
but  build still fails, because of missing google-services.json

**Comment by dshokouhi** [comment]
> 5\. Now download the `google-services.json` file and put it in the project's _/app_, _/automotive_ and _/wear_ folders.



> I have placed the mockgoogle-service.json (as google-services.json) file in both locations
> _/media/ich/1TB_SSD/AndroidApks/temp/android/common/ 
> /media/ich/1TB_SSD/AndroidApks/temp/android/wear_

should be 3 locations, and the first one is incorrect

**Comment by dshokouhi** [comment]
please stop opening new project build issues in this repo, this is not hte correct location

https://github.com/home-assistant/android

**Comment by LeOS-GSI** [comment]
> _/media/ich/1TB_SSD/AndroidApks/temp/android/common/_

was my mistake/mistyping. it was located in automotive.

And nice, after adding in 3rd location /app  build finish successful.

**Comment by LeOS-GSI** [comment]
now I need to check how to remove the AltBeacon tracker. If you will have any suggestion, I will be very thankful
