### ISSUE TITLE
Blank Pages and freeze + OSError: [Errno 24] Too many open files since the last update 2024.3.0

### ISSUE THREAD

**Issue by ALaDoffe** [home-assistant/companion.home-assistant#1053]
Hello,

Since the last update, Companion App becomes very laggy on my devices.
When two people are trying to open HA in same time, it'sunusable.
In parrallel I get a lot of error below in HA log.

```
2024-04-02 13:56:37.948 ERROR (MainThread) [homeassistant] Error doing job: socket.accept() out of system resource
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 178, in _accept_connection
  File "/usr/local/lib/python3.12/socket.py", line 295, in accept
OSError: [Errno 24] Too many open files
```

Indeed, i get :
```
pi@raspberrypi:~ $ sudo lsof | grep hass | wc -l
80957
pi@raspberrypi:~ $ sudo netstat -nap | grep 8123 | wc -l
851
```

I have already try to reset the cache frontend but no success.

Thx for help.

My conf: 
RPI3B+ 
BookWorm 32Bits
Python 3.12.2
HA core 2024.3.3 on venv
IOS : 17.4.1
Companion : 2024.3.0

**Comment by dshokouhi** [comment]
@ALaDoffe you have opened an issue against the documentation. Please open an issue in the actual iOS repo https://github.com/home-assistant/iOS
