### ISSUE TITLE
Subtitle not shown in documentation

### ISSUE THREAD

**Issue by caco3** [home-assistant/companion.home-assistant#1085]
On https://companion.home-assistant.io/docs/notifications/critical-notifications/, the title for the `Android` section somehow is not shown, at least on Firefox and Chromium under Linux:
![grafik](https://github.com/user-attachments/assets/5c3282a4-f450-40ce-b24f-d355e72668f1)

The one above for iOS is shown correctly.

**Comment by jpelgrom** [comment]
There is no additional title, it only includes the icon.

The icon for the iOS/iPadOS/watchOS/Mac app includes an Apple icon *and* iOS, the icon for the Android app (all form factors) is only the bugdroid. This is applied consistently in the documentation.

**Comment by caco3** [comment]
OK, I see.

But IMO this is really unfortunate as most normal users will not identify that icon as the start of the Android section!
I actually only found it because I clicked on the Android entry on the navigation in the side bar!

My proposal really would be to show the OS name beside the icon.
