### ISSUE TITLE
Change the logo of login page

### ISSUE THREAD

**Issue by Sini-Shahanas** [home-assistant/companion.home-assistant#1106]
Is it possible to change the logo in the login page of HA companion app? Where can I find the login page (authentication) code file?

**Comment by jpelgrom** [comment]
This is not the right place for questions like these. Try asking on the [forums](http://community.home-assistant.io/) or [Discord](https://www.home-assistant.io/join-chat/). The logo is provided by the frontend so you'll want to ask about customizing the frontend.
