### ISSUE TITLE
Duplicate Records in Companion App Integration

### ISSUE THREAD

**Issue by vbueschken** [home-assistant/companion.home-assistant#1115]
This Issue is reported since Jul,26 2024 - may be in a wrong context /location (under 'core')
Seams nobody takes care about this .

Please look at:
https://github.com/home-assistant/core/issues/122794#issuecomment-2383521354

Thanks
Volker

**Comment by dshokouhi** [comment]
please do not file bugs in other locations just wait for the original issue to get responded to.

**Comment by vbueschken** [comment]
Sorry Daniel... I thought the Issue was reported on the wrong place, because it is related to the companion App / Integration

**Comment by dshokouhi** [comment]
admittedly it can be a lil confusing around the mobile apps (too many moving parts), the error in the thread is a HA core error and can only be solved there. This repo is only about issues with the companion app documentation. Issues with apps themselves can be reported in teh appropriate repo.
