### ISSUE TITLE
Add more Health Connect sensor

### ISSUE THREAD

**Issue by caohuongls** [home-assistant/companion.home-assistant#1137]
Thanks for adding Health Connect to Home Assistant. Everything seems to be working smoothly. I’m hoping we can add even more sensors like:

- Vo2Max
- Oxygen Saturation
- Lean Body Mass
- Height
- Basal Metabolic Rate
- Bone Mass
- Respiratory Rate

**Comment by dshokouhi** [comment]
feature requets are not accepted here
