### ISSUE TITLE
Docs missing for: Enable receiving broadcast to update location

### ISSUE THREAD

**Issue by allanpersson** [home-assistant/companion.home-assistant#156]
It seems (i searched every doc page without finding at least) there is missing documentation about the feature **Enable receiving broadcast to update location** introduced in Home Assistant Companion Android 1.7.0.
Link to PR https://github.com/home-assistant/home-assistant-android/pull/355

**Comment by klaasnicolaas** [comment]
I think that it's this page: https://companion.home-assistant.io/docs/notifications/location-notification

**Comment by allanpersson** [comment]
I might be wrong but I think it's 2 different features!?
Request location https://github.com/home-assistant/home-assistant-android/pull/333 is a message. And I think this one is broadcasting location through an app (Tasker etc)?

Correct me if I'm wrong 🙏

**Comment by robbiet480** [comment]
@quthla Mind whipping up some docs for this? I would do it myself but I'm not exactly sure what the feature is. Thanks!

**Comment by quthla** [comment]
It's a feature rather for developers than for end users.

It means that you can send a broadcast intent with action `io.homeassistant.companion.android.background.REQUEST_ACCURATE_UPDATE` from another app or Tasker to trigger a location update.

**Comment by dshokouhi** [comment]
@quthla I was honestly meaning to ask you to document this for us since I wasn't sure how it works :) As the user can use Tasker to use this feature then we should definitely get it documented for everyone to enjoy.  I am sure lots of Android users already have and use Tasker.

**Comment by quthla** [comment]
I don't use Tasker so I can't really help you there. But if you use Tasker, look for something reading broadcast or so and if you get it working, maybe write the steps down.

**Comment by dshokouhi** [comment]
Hmm I do not see a way to add this in Tasker. It may just be my own understanding of tasker since I do see intents there.  Maybe someone else can figure it out :)

**Comment by allanpersson** [comment]
@dshokouhi thanks for your awesome effort in doing support on the issues and organizing things, your effort is not going unnoticed 👏
