### ISSUE TITLE
Add package-lock.json file to repo

### ISSUE THREAD

**Issue by klaasnicolaas** [home-assistant/companion.home-assistant#174]
A suggestion from me: is it a handy addition to include a `package-lock.json` file in the repo by default? 

Since `npm install` uses this to install all packages, this also ensures that everyone that is working on the companion docs uses the same packages with local development.

Just think about it 😉

**Comment by robbiet480** [comment]
PRs welcome :)

**Comment by klaasnicolaas** [comment]
Well I wanted to introduce it first before I immediately generate a PR with a lock file 😆

**Comment by TomBrien** [comment]
Our preferred package manager and build commands are `yarn` so I would say this is satisfied already.

**Comment by klaasnicolaas** [comment]
Well I think we can close this one
