### ISSUE TITLE
Search result links are going to wrong location

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/companion.home-assistant#179]
Looks like the search result link locations need to be updated.  

Example: searching for `Location` leads to

https://companion.home-assistant.io/en/core/location#__docusaurus

while it should be: https://companion.home-assistant.io/docs/core/location

So far it seems to be impacting all results.  Not entirely sure where the issue relies.  We had a similar issue with the links on the feature comparison table and I had to update them to be exact locations.

**Comment by TomBrien** [comment]
This is currently a known bug. We are hoping it just needs to be crawled by Agolia again which happens every 24 hours

**Comment by TomBrien** [comment]
So little update on this.

I note that looking at our [`sitemap.xml`](https://companion.home-assistant.io/sitemap.xml) that docusaurus sets the `changefreq` to weekly for all pages. I don't know if Algolia uses that. I'll request the re run the scrapper now

**Comment by TomBrien** [comment]
You can find the issue I've raised with Algolia here: algolia/docsearch-config#1667

**Comment by TomBrien** [comment]
Crawler has been re run and all is working now
