### ISSUE TITLE
Cross platform way to link to your HA app

### ISSUE THREAD

**Issue by clofresh** [home-assistant/companion.home-assistant#251]
Hello,

I want to link my local HA install from a landing page in my internal network. Is there a single link that will try to open an installed mobile app whether ios or android, but if it doesn't exist, fall back to the web location? I think it's a fairly common use case, so it would be worth documenting if it were possible.

**Comment by TomBrien** [comment]
This is being discussed in home-assistant/ios#643 so hopefully it will come in soon

**Comment by zacwest** [comment]
`homeassistant://navigate/lovelace/dashboard` will open `/lovelace/dashboard` in iOS, macOS and Android
