### ISSUE TITLE
Clarification needed in dynamic notifcation docs

### ISSUE THREAD

**Issue by jeffehobbs** [home-assistant/companion.home-assistant#414]
This should be a pretty quick fix.

On [this page](https://companion.home-assistant.io/docs/notifications/dynamic-content), it says:

`You may also use a device_tracker for the latitude and longitude coordinates like so: "{{states.device_tracker.<your_device_id_here>.attributes.latitude}}" but make sure to use data_template in that case.`

As the automation has two levels of data object, these docs should be clarified to specify which data object should be specified as a data_template: the first, the second, or both.

**Comment by TomBrien** [comment]
Actually these are out of data now. Neither needs to be change to `data_template` any more. We should update to reflect that

**Comment by jeffehobbs** [comment]
Oh really! Well this explains a lot. Where do those go now?

**Comment by TomBrien** [comment]
Right now there is a bug in Home Assistant that is sending template data through wrong on these. It will be addressed in the next app version
