### ISSUE TITLE
Readme has time wasting typo

### ISSUE THREAD

**Issue by PedroKTFC** [home-assistant/companion.home-assistant#455]
It's a trivial point I know but I didn't spot it for ages and caused me lots of frustration and I suspect I'm not the only one.

In the configuration.yaml text at the end, there's a typo in the line (in capitals so it's easy to see):

\# ssl_certificate: /ssl/fullchai**M**.pem

It should be:

\# ssl_certificate: /ssl/fullchai**N**.pem

I would edit the file directly but it requires me to fork etc, something I've never done on github so don't want to break anything.

**Comment by TomBrien** [comment]
Using the "Edit this page" link should do the forking etc. automatically. Don't worry you wont break anything ;)

**Comment by PedroKTFC** [comment]
Well Tom, I've corrected it so if things go tits up don't blame me! :o)

**Comment by TomBrien** [comment]
Closed via #457
