### ISSUE TITLE
Browser_mod deviceID

### ISSUE THREAD

**Issue by sylviepipi** [home-assistant/companion.home-assistant#554]
I'm using home companion as KIOSK together with browser_mod on an IPAD.
Whenever i reboot home assistant the device_id is not available untill i forcefully restart home companion.
I would be great of we could restart home companion using a service call so i can make an automation whenever home assistant starts to restart the kiosk.

**Comment by dshokouhi** [comment]
this request is actually not in the correct location, as this is related to browser mod I suggest starting in that repo.
