### ISSUE TITLE
Resetting and mobile_app in .storage

### ISSUE THREAD

**Issue by uowis** [home-assistant/companion.home-assistant#637]
Hi !
https://companion.home-assistant.io/docs/troubleshooting/resetting/
In this Page it explain to delete mobile_app  file in .storage folder
I have delete it but it never come back or regenerate...

**Comment by dshokouhi** [comment]
@uowis did you make sure to restart HA and log back into the app? Under normal circumstances you dont need to delete that file.

**Comment by uowis** [comment]
Okay mobil_app File regenerate with connexion to new mobil.
