### ISSUE TITLE
On beta companion: App on Wear OS "Could not connect"

### ISSUE THREAD

**Issue by LudoOne** [home-assistant/companion.home-assistant#657]
After configuring host: "http://192.168.1.204:8123"
error appears "Could not connect" with an image of a disgruntled cloud.

Watch is on Wifi and has valid IP and internet access
Host is a functioning Raspberry Pi 4 on LAN with Home Assistant 2021.12.8
Device is an OPPO Watch model OW19W8 with Wear OS version 9

**Comment by dshokouhi** [comment]
This is fixed in the latest beta which will be on the play store tonight
