### ISSUE TITLE
Example for Actionable Notifications should mention that it blocks if notification is discarded

### ISSUE THREAD

**Issue by tamueller** [home-assistant/companion.home-assistant#701]
The example for actionable notifications here: https://companion.home-assistant.io/docs/notifications/actionable-notifications/ has a small caveat:

If the automation mode is set to Single, Queue or Parallel this will stop working once the notification is discarded in android (often enough). The trigger waits for one of the action, but if none of the actions is received, it will simply wait there, and block further executions of the automation.
There are two possible solutions for this: Either, briefly explain the problem and recommend using "restart" mode, or extend the example to also handle the "mobile_app_notification_cleared" event. I achieved this by simply adding:

`      - platform: event
        event_type: mobile_app_notification_cleared
        event_data:
          action_1_key: '{{ action_open }}'
`

I think the latter makes the example a little bit more helpful, but also more versatile, as the user immediately understands, that he can/should also handle the cleared event. Let me know if you want me to update the documentation or example-code.

**Comment by dshokouhi** [comment]
> The trigger waits for one of the action, but if none of the actions is received, it will simply wait there, and block further executions of the automation.
> There are two possible solutions for this: Either, briefly explain the problem and recommend using "restart" mode, or extend the example to also handle the "mobile_app_notification_cleared" event. 

Actually you can also implement a `timeout` too so maybe it makes sense to have a considerations section?

https://www.home-assistant.io/docs/scripts/#wait-timeout

> I think the latter makes the example a little bit more helpful, but also more versatile, as the user immediately understands, that he can/should also handle the cleared event.

while it does make sense for android that means we will have to maintain 2 examples as the current example is compliant with iOS too

> Let me know if you want me to update the documentation or example-code.

Please feel free to do so, the docs only get better as we all come together to update them :)

**Comment by tamueller** [comment]
@dshokouhi : Just a question, since I'm new to contributing to HA: Do I have to ask anyone directly to merge the pull request, or will this happen by itself if someone finds time?

**Comment by dshokouhi** [comment]
> @dshokouhi : Just a question, since I'm new to contributing to HA: Do I have to ask anyone directly to merge the pull request, or will this happen by itself if someone finds time?

PR's will get reviewed when one of us finds the time, we get notified when they are submitted :)
