### ISSUE TITLE
Typo in Basic Notifications Page (sounds:) should be sound:

### ISSUE THREAD

**Issue by bryeartem** [home-assistant/companion.home-assistant#77]
It seems the example under:
https://companion.home-assistant.io/en/next/notifications/basic#notification-sounds
has the word "sounds:" when it should be "sound:"

Sorry if this isn't the correct way to get this corrected.

**Comment by robbiet480** [comment]
There should be a Edit button on that page. Hit that and you can submit the fix yourself and I’ll merge it :smile:

**Comment by TomBrien** [comment]
As this has been sitting for a little while, I have fixed and will close this.
