### ISSUE TITLE
Action drop-down

### ISSUE THREAD

**Issue by smolders33** [home-assistant/companion.home-assistant#832]
In the one action widget I can not change to another action.
Rebooted already my phone.

**Comment by smolders33** [comment]
![image](https://user-images.githubusercontent.com/50782886/193657247-597d516d-fc67-4765-bd58-1d8febc33c62.png)

**Comment by dshokouhi** [comment]
Please open an issue in https://github.com/home-assistant/ios as this repository is only for documentation. Also make sure to fill out the issue template completely over there.
