### ISSUE TITLE
Allow microphone usage for insecure connections

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/companion.home-assistant#941]
Hello
now that the year of the voice has added the Assist feature, I wanted to test it with Piper and Whisper but the mic does not work in the Companion app without SSL connection.

Now I appreciate a certain level of safety, but in purely local systems SSL is superfluous.

Could an option please be added to allow mic usage without SSL?

Afaik this is not a browser limitation as they can be set to allow insecure connections.

Thank you and best regards
Alex

**Comment by jpelgrom** [comment]
> Afaik this is not a browser limitation as they can be set to allow insecure connections.

At least for Android, it is: home-assistant/android#3512

**Comment by AleXSR700** [comment]
Well, is it a feature request or a bug?
Home Assistant does not support ssl connections for local servers. All instructions seem to be outdated and a purely local server cannot run DuckDNS or VPN services.

So we have a feature that is not supported by the system. Should there not be a solution to this without needing to install a VPN service or other third-party service?
