### ISSUE TITLE
Back & Hamburger Button on "Error while loading page lovelace." screen malfunction

### ISSUE THREAD

**Issue by heyhewmike** [home-assistant/companion.home-assistant#942]
When there is an issue with the Server URL and the Lovelace UI is unable to load the lovelace page the back button and the Hamburger Menu Page is not accessible. There is no way to access the app to make any changes to the URL or settings that might be preventing the lovelace UI from loading.

*** My issue is that the External URL is currently incorrect or my firewall is incorrectly configured.

Please see the attached screen-recording showing my interactions with the app (version 2023.3-full), Android 13 Build TQ2A.230505.002

https://github.com/home-assistant/companion.home-assistant/assets/75391794/118c68f5-6200-49e1-8405-7064e789ac8f

**Comment by jpelgrom** [comment]
Hi,

This is a frontend issue, not a documentation issue, and not something the app can handle. Please create an issue in the frontend repository about no possibility to open the menu (though I expect they will need more details/logs, which will be hard to get to).

If you completely close the app, enable airplane mode, and re-open the app, it'll probably give you a pop-up after 10 seconds that allows you to go to the app settings.

**Comment by heyhewmike** [comment]
> Hi,
> 
> This is a frontend issue, not a documentation issue, and not something the app can handle. Please create an issue in the frontend repository about no possibility to open the menu (though I expect they will need more details/logs, which will be hard to get to).
> 
> If you completely close the app, enable airplane mode, and re-open the app, it'll probably give you a pop-up after 10 seconds that allows you to go to the app settings.

Thank you. I did not understand this was purely a documentation repository for the companion app.

Thank you for the tip.

**Comment by jpelgrom** [comment]
You're welcome, hopefully you can get into the settings instead of having to reset the app :)
