### ISSUE TITLE
Searches for Home Assistant Server

### ISSUE THREAD

**Issue by Jens3091** [home-assistant/companion.home-assistant#954]
Searching for Home Assistant Server for 10min.

![Screenshot_20230709_171938_Home Assistant](https://github.com/home-assistant/companion.home-assistant/assets/139062750/e6971174-58ca-4b70-b0a1-e5398b63380f)

**Comment by dshokouhi** [comment]
Not every device can find your server locally that is why the manual button is the below. Also this is not the correct location to file a bug. This repo is for doc issues only.

**Comment by Jens3091** [comment]
I don't know, where then

**Comment by dshokouhi** [comment]
https://github.com/home-assistant/android is the correct location to file bugs found in the app
