### ISSUE TITLE
Does the home assitant android app have requirements for the android version

### ISSUE THREAD

**Issue by Lico-Tom** [home-assistant/companion.home-assistant#958]
Excuse me. Does the home assitant android app have requirements for the android version
I had a situation
![微信图片_20230715160226](https://github.com/home-assistant/companion.home-assistant/assets/95178212/3ac343b9-4dfa-43d0-8521-87a1867be10d)
aandroid version 8.0.0

**Comment by dshokouhi** [comment]
This looks like a possible outdated WebView issue. Make sure it's fully up to date from the play store. The app supports Android 5+

**Comment by Lico-Tom** [comment]
this is latest version.
&nbsp;


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2023年7月15日(星期六) 下午4:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [home-assistant/companion.home-assistant] Does the home assitant android app have requirements for the android version (Issue #958)





 
This looks like a possible outdated WebView issue. Make sure it's fully up to date from the play store. The app supports Android 5+

**Comment by Lico-Tom** [comment]
It's fine to install it on a phone, but it's a problem when you install it on a ipad



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "home-assistant/companion.home-assistant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月15日(星期六) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [home-assistant/companion.home-assistant] Does the home assitant android app have requirements for the android version (Issue #958)





 
This looks like a possible outdated WebView issue. Make sure it's fully up to date from the play store. The app supports Android 5+

**Comment by Lico-Tom** [comment]
Is there any way to know the abnormal information reported by the app

**Comment by dshokouhi** [comment]
> this is latest version. &nbsp; . ***@***.*** &nbsp;

yes but is it Googles version from the play store?



> It's fine to install it on a phone, but it's a problem when you install it on a ipad &nbsp;

im sorry the android app cannot be installed on the ipad



> Is there any way to know the abnormal information reported by the app

I am not sure what you are referring to but this is not the correct place to file a bug report, please report in either [android](https://github.com/home-assistant/android/issues/new?assignees=&labels=bug&projects=&template=Bug_report.md&title=) or [iOS](https://github.com/home-assistant/iOS/issues/new?assignees=&labels=bug%2C+ios&projects=&template=bug_report_iOS.md&title=)

I am going to close this issue as this repo is only for issues with the documentation
