### ISSUE TITLE
Complication does not auto update

### ISSUE THREAD

**Issue by KentEkl** [home-assistant/companion.home-assistant#986]
Since iOS 17 and watchOS 10 my watch complication does not update automatic anymore, I have to do it manually.

**Comment by dshokouhi** [comment]
This is the wrong place to submit an iOS issue unfortunately, please submit an issue in the following location

https://github.com/home-assistant/iOS/issues/new?assignees=&labels=bug%2C+ios&projects=&template=bug_report_iOS.md&title=
